import { createHash } from "node:crypto";
import type { CanonicalIR, IRProperty } from "./ir";
import { stableStringify } from "./ir";

/**
 * 编译器：Canonical IR → 确定性生成物（spec §14）。
 * 所有产物只依赖 IR 内容；无时间戳、无环境差异。
 */

export interface CompiledArtifacts {
  /** 文件名 → 文本内容（LF 结尾） */
  files: Record<string, string>;
  fingerprint: string;
}

export function computeFingerprint(ir: CanonicalIR): string {
  return createHash("sha256").update(stableStringify(ir), "utf8").digest("hex");
}

function jsonSchemaForType(ir: CanonicalIR, typeId: string): Record<string, unknown> {
  const t = ir.objectTypes[typeId];
  const properties: Record<string, unknown> = {};
  const required: string[] = [];
  for (const [name, prop] of Object.entries(t.properties)) {
    properties[name] = jsonSchemaForProperty(ir, prop);
    if (prop.required) required.push(name);
  }
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: typeId,
    type: "object",
    properties,
    required,
    additionalProperties: false,
  };
}

function jsonSchemaForProperty(ir: CanonicalIR, prop: IRProperty): Record<string, unknown> {
  const listMatch = /^list<([a-z]+)>$/.exec(prop.type);
  if (listMatch) {
    return { type: "array", items: jsonSchemaForProperty(ir, { ...prop, type: listMatch[1] }) };
  }
  if (prop.type === "enum") {
    const vs = prop.ref ? ir.valueSets[prop.ref] : undefined;
    return { type: "string", enum: vs ? vs.values : [] };
  }
  switch (prop.type) {
    case "uuid":
      return { type: "string", format: "uuid" };
    case "string":
      return { type: "string", maxLength: 512 };
    case "text":
      return { type: "string" };
    case "integer":
      return { type: "integer" };
    case "decimal":
      // 金额以字符串传输，禁止 float 语义
      return { type: "string", pattern: "^-?[0-9]+(\\.[0-9]+)?$" };
    case "boolean":
      return { type: "boolean" };
    case "date":
      return { type: "string", format: "date" };
    case "datetime":
      return { type: "string", format: "date-time" };
    case "uri":
      return { type: "string", format: "uri" };
    case "json":
      return {};
    default:
      return { type: "string" };
  }
}

function tsTypeForProperty(ir: CanonicalIR, prop: IRProperty): string {
  const listMatch = /^list<([a-z]+)>$/.exec(prop.type);
  if (listMatch) {
    return `${tsTypeForProperty(ir, { ...prop, type: listMatch[1] })}[]`;
  }
  if (prop.type === "enum") {
    const vs = prop.ref ? ir.valueSets[prop.ref] : undefined;
    return vs && vs.values.length > 0 ? vs.values.map((v) => JSON.stringify(v)).join(" | ") : "string";
  }
  switch (prop.type) {
    case "uuid":
    case "string":
    case "text":
    case "date":
    case "datetime":
    case "uri":
      return "string";
    case "decimal":
      return "string"; // 十进制定点 wire format
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "json":
      return "unknown";
    default:
      return "string";
  }
}

function renderTypesTs(ir: CanonicalIR): string {
  const lines: string[] = [
    "/* eslint-disable */",
    "// AUTO-GENERATED by @daka/ontology-dsl compile — 禁止手改",
    `// ontology: ${ir.meta.name}@${ir.meta.version} dsl=${ir.meta.dsl}`,
    "",
  ];
  for (const [id, vs] of Object.entries(ir.valueSets)) {
    lines.push(`export type ${pascal(id)} = ${vs.values.map((v) => JSON.stringify(v)).join(" | ")};`);
  }
  lines.push("");
  for (const [id, t] of Object.entries(ir.objectTypes)) {
    lines.push(`export interface ${id} {`);
    lines.push(`  id: string;`);
    for (const [name, prop] of Object.entries(t.properties)) {
      if (name === "id") continue; // 平台注入，已输出
      const optional = prop.required ? "" : "?";
      lines.push(`  ${name}${optional}: ${tsTypeForProperty(ir, prop)};`);
    }
    lines.push(`}`);
    lines.push("");
    const derivedNames = Object.keys(t.derived);
    if (derivedNames.length > 0) {
      lines.push(`export interface ${id}Derived {`);
      for (const [name, prop] of Object.entries(t.derived)) {
        lines.push(`  ${name}: ${tsTypeForProperty(ir, prop)};`);
      }
      lines.push(`}`);
      lines.push("");
    }
  }
  for (const [id, action] of Object.entries(ir.actions)) {
    const inputFields = Object.entries(action.inputs)
      .map(([name, prop]) => `  ${name}${prop.required ? "" : "?"}: ${tsTypeForProperty(ir, prop)};`)
      .join("\n");
    lines.push(`export interface ${pascal(id)}Input {`);
    lines.push(inputFields || "  // 无输入");
    lines.push(`}`);
    lines.push("");
  }
  return lines.join("\n");
}

function pascal(id: string): string {
  return id.charAt(0).toUpperCase() + id.slice(1);
}

function renderOpenApi(ir: CanonicalIR): Record<string, unknown> {
  const paths: Record<string, unknown> = {
    "/v1/meta/ontology": {
      get: { summary: "Ontology manifest 元信息", responses: { "200": { description: "OK" } } },
    },
    "/v1/facts/{id}/verify": { post: { summary: "确认 proposed 事实", responses: { "200": { description: "OK" } } } },
    "/v1/facts/{id}/reject": { post: { summary: "驳回 proposed 事实", responses: { "200": { description: "OK" } } } },
    "/v1/facts/{id}/supersede": { post: { summary: "替代已确认事实", responses: { "200": { description: "OK" } } } },
    "/v1/ingest/validate": { post: { summary: "Data Pack 校验（dry-run）", responses: { "200": { description: "OK" } } } },
    "/v1/ingest/apply": { post: { summary: "Data Pack 事务性导入", responses: { "200": { description: "OK" } } } },
    "/v1/ingest/jobs/{id}": { get: { summary: "同步任务状态", responses: { "200": { description: "OK" } } } },
    "/v1/audit": { get: { summary: "审计事件查询", responses: { "200": { description: "OK" } } } },
    "/health/live": { get: { summary: "liveness", responses: { "200": { description: "OK" } } } },
    "/health/ready": { get: { summary: "readiness", responses: { "200": { description: "OK" } } } },
  };
  for (const typeId of Object.keys(ir.objectTypes)) {
    paths[`/v1/objects/${typeId}`] = {
      get: { summary: `查询 ${typeId}`, responses: { "200": { description: "OK" } } },
      post: { summary: `创建 ${typeId}`, responses: { "200": { description: "OK" } } },
    };
  }
  for (const actionId of Object.keys(ir.actions)) {
    paths[`/v1/actions/${actionId}/execute`] = {
      post: { summary: `执行 ${actionId}（幂等键必需）`, responses: { "200": { description: "OK" }, "403": { description: "policy denial" }, "409": { description: "version conflict" }, "422": { description: "precondition failed" } } },
    };
  }
  for (const projId of Object.keys(ir.projections)) {
    paths[`/v1/projections/${projId}`] = {
      get: { summary: `读取投影 ${projId}`, responses: { "200": { description: "OK" } } },
    };
  }
  return {
    openapi: "3.1.0",
    info: { title: `${ir.meta.name} Ontology Runtime API`, version: ir.meta.version },
    paths: Object.fromEntries(Object.entries(paths).sort(([a], [b]) => a.localeCompare(b))),
  };
}

/** 声明式索引计划：状态枚举、外键 id、时间字段进入 B-tree；JSONB 扩展列由 Runtime 约定。 */
function renderIndexPlan(ir: CanonicalIR): Record<string, unknown> {
  const indexes: Array<Record<string, unknown>> = [];
  for (const [typeId, t] of Object.entries(ir.objectTypes)) {
    for (const [name, prop] of Object.entries(t.properties)) {
      if (name === "id") continue;
      const isEnum = prop.type === "enum";
      const isFk = name.endsWith("Id") && prop.type === "uuid";
      const isTime = prop.type === "datetime" || prop.type === "date";
      if (isEnum || isFk || isTime) {
        indexes.push({
          objectType: typeId,
          column: name,
          kind: "btree",
          reason: isEnum ? "enum_status" : isFk ? "foreign_reference" : "temporal_query",
        });
      }
    }
  }
  indexes.sort((a, b) =>
    `${a.objectType}.${a.column}`.localeCompare(`${b.objectType}.${b.column}`),
  );
  return {
    generator: "@daka/ontology-dsl index-plan v1",
    tenantIsolation: ["tenant_id", "workspace_id"],
    indexes,
  };
}

export function compileIR(ir: CanonicalIR): CompiledArtifacts {
  const fingerprint = computeFingerprint(ir);
  const manifest = { ...ir, fingerprint };
  const schema: Record<string, unknown> = {};
  for (const typeId of Object.keys(ir.objectTypes)) {
    schema[typeId] = jsonSchemaForType(ir, typeId);
  }
  return {
    fingerprint,
    files: {
      "ontology.manifest.json": stableStringify(manifest),
      "ontology.schema.json": stableStringify(schema),
      "ontology.types.ts": renderTypesTs(ir),
      "ontology.openapi.json": stableStringify(renderOpenApi(ir)),
      "ontology.index-plan.json": stableStringify(renderIndexPlan(ir)),
      "ontology.fingerprint": fingerprint + "\n",
    },
  };
}
