/* eslint-disable */
// AUTO-GENERATED by @daka/ontology-dsl compile — 禁止手改
// ontology: daka-business-ontology@1.0.0 dsl=1

export type ContractStatus = "active" | "draft" | "expired" | "terminated" | "under_review";
export type FactStatus = "proposed" | "rejected" | "superseded" | "verified";
export type LifecycleStage = "approval" | "contracting" | "designing" | "production" | "sampling" | "selling" | "settlement" | "sourcing" | "warehousing";
export type PaymentStatus = "disputed" | "due" | "overdue" | "paid" | "planned" | "waived";
export type RecommendationStatus = "approved" | "in_review" | "rejected" | "suggested";
export type RecommendationType = "delist" | "hold" | "price_adjust" | "reprint";
export type RiskSeverity = "critical" | "high" | "info" | "low" | "medium";
export type RiskStatus = "acknowledged" | "dismissed" | "open" | "resolved";
export type SecurityLevel = "confidential" | "highly_confidential" | "internal";
export type SignatureMovementType = "adjusted" | "allocated" | "consumed" | "granted" | "inspected" | "received" | "returned";

export interface Affiliation {
  id: string;
  affiliationType: string;
  validFrom?: string;
  validTo?: string;
}

export interface Contract {
  id: string;
  contractNumber?: string;
  documentId: string;
  effectiveFrom?: string;
  effectiveTo?: string;
  governingLaw?: string;
  signedAt?: string;
  status: "active" | "draft" | "expired" | "terminated" | "under_review";
  title: string;
}

export interface Document {
  id: string;
  capturedAt: string;
  mediaType: string;
  sha256: string;
  uri: string;
  version: string;
}

export interface EvidenceAnchor {
  id: string;
  documentId: string;
  excerptHash?: string;
  locator: unknown;
  locatorType: string;
}

export interface FactAssertion {
  id: string;
  assertedBy: string;
  confidence?: string;
  evidenceAnchorId: string;
  objectValue: unknown;
  predicate: string;
  recordedAt: string;
  status: "proposed" | "rejected" | "superseded" | "verified";
  subjectId: string;
  supersedesFactId?: string;
  validFrom?: string;
  validTo?: string;
}

export interface FootballClub {
  id: string;
  countryOrRegion?: string;
  league?: string;
}

export interface MarketObservation {
  id: string;
  currency: string;
  notes?: string;
  observedAt: string;
  premiumRate?: string;
  salePrice?: string;
  source: string;
  spread?: string;
  turnoverRate?: string;
  uniqueBuyers?: number;
  volume?: number;
  windowDays: number;
}

export interface MilestoneEvidence {
  id: string;
  evidenceAnchorId?: string;
  milestoneType: string;
  occurredAt?: string;
  status: string;
}

export interface Obligation {
  id: string;
  completionStatus: string;
  description: string;
  dueAt?: string;
  obligationType: string;
}

export interface Party {
  id: string;
  legalName: string;
  partyType: string;
  registrationIdentifier?: string;
}

export interface Payment {
  id: string;
  amount: string;
  currency: string;
  paidAt: string;
  transactionReference?: string;
}

export interface PaymentSchedule {
  id: string;
  amount: string;
  currency: string;
  dueAt: string;
  status: "disputed" | "due" | "overdue" | "paid" | "planned" | "waived";
  triggerCondition?: string;
}

export interface PaymentScheduleDerived {
  settledAmount: string;
  unsettledAmount: string;
}

export interface ReleaseProject {
  id: string;
  ownerId: string;
  plannedLaunchAt?: string;
  projectName: string;
  stage: "approval" | "contracting" | "designing" | "production" | "sampling" | "selling" | "settlement" | "sourcing" | "warehousing";
}

export interface ReleaseProjectDerived {
  activeRightsCoverage: string[];
}

export interface ReleaseRecommendation {
  id: string;
  createdAt: string;
  createdBy: string;
  metricSnapshot?: unknown;
  rationale: string;
  recommendationType: "delist" | "hold" | "price_adjust" | "reprint";
  reviewComment?: string;
  reviewedAt?: string;
  status: "approved" | "in_review" | "rejected" | "suggested";
}

export interface RightsGrant {
  id: string;
  approvalRequired?: boolean;
  channel?: string[];
  exclusivity?: string;
  productCategory?: string[];
  rightType: string;
  territory?: string[];
  validFrom: string;
  validTo: string;
}

export interface RiskFinding {
  id: string;
  evidenceAnchorIds?: string[];
  explanation: string;
  riskType: string;
  ruleId?: string;
  severity: "critical" | "high" | "info" | "low" | "medium";
  status: "acknowledged" | "dismissed" | "open" | "resolved";
  subjectId?: string;
}

export interface SignatureEntitlement {
  id: string;
  constraints?: string;
  grantedQuantity: number;
  unit: string;
  validFrom?: string;
  validTo?: string;
}

export interface SignatureLot {
  id: string;
  lotNumber: string;
  qualityStatus?: string;
  receivedAt: string;
  receivedQuantity: number;
}

export interface SignatureLotDerived {
  allocatedQuantity: number;
  availableQuantity: number;
  consumedQuantity: number;
}

export interface SignatureMovement {
  id: string;
  actorId: string;
  movementType: "adjusted" | "allocated" | "consumed" | "granted" | "inspected" | "received" | "returned";
  occurredAt: string;
  quantity: number;
  reason?: string;
}

export interface SKU {
  id: string;
  category: string;
  productName: string;
  skuCode: string;
}

export interface Talent {
  id: string;
  alternateNames?: string[];
  canonicalName: string;
  identityIdentifier?: string;
}

export interface TVSeries {
  id: string;
  productionCompany?: string;
  releaseYear?: number;
}

export interface AllocateSignaturesInput {
  quantity: number;
  reason?: string;
  releaseProjectId: string;
}

export interface ConfirmFactInput {
  factId: string;
  reviewComment?: string;
}

export interface ExtractContractCandidatesInput {
  contractId: string;
  extractorVersion: string;
}

export interface ReceiveSignatureLotInput {
  evidenceAnchorId: string;
  lotNumber: string;
  quantity: number;
  receivedAt: string;
}

export interface RecordPaymentInput {
  amount: string;
  currency: string;
  paidAt: string;
  transactionReference?: string;
}

export interface RejectFactInput {
  factId: string;
  rejectionReason: string;
}

export interface ResolveContractRiskInput {
  evidenceAnchorId: string;
  resolution: string;
}

export interface ReviewReleaseRecommendationInput {
  decision: "approved" | "in_review" | "rejected" | "suggested";
  reviewComment?: string;
}

export interface SupersedeFactInput {
  oldFactId: string;
  reason: string;
  replacementFact: unknown;
}

export interface UploadContractInput {
  documentUri: string;
  sha256: string;
  title: string;
}
